### ISSUE TITLE
Not suitable for symlinked environments

### ISSUE THREAD

**Issue by phth** [Digi92/dw_content_elements#2]
\Denkwerk\DwContentElements\Service\Ini fails to load the given config files. Reason is, that the configFileAbsPath \Denkwerk\DwContentElements\Service\Ini->loadConfig() is build wrong: 

``` php
$this->configFileAbsPath = \Denkwerk\DwContentElements\Utility\Pathes::concat(array(realpath(PATH_site), realpath($this->configFile)));
```

If you combine two paths generated by realpath(), you will get doubled path segments. For me, it worked when i replaced the mentioned line with 

``` php
$this->configFileAbsPath = $this->configFile;
```

**Comment by Digi92** [comment]
This code was rewritten some time ago
